USE [master]
GO
/****** Object:  Database [Agil]    Script Date: 25/02/2022 11:17:37 ******/
CREATE DATABASE [Agil]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Agil', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\Agil.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Agil_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\Agil_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Agil] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Agil].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Agil] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Agil] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Agil] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Agil] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Agil] SET ARITHABORT OFF 
GO
ALTER DATABASE [Agil] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Agil] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Agil] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Agil] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Agil] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Agil] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Agil] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Agil] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Agil] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Agil] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Agil] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Agil] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Agil] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Agil] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Agil] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Agil] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Agil] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Agil] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Agil] SET  MULTI_USER 
GO
ALTER DATABASE [Agil] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Agil] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Agil] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Agil] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Agil] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Agil] SET QUERY_STORE = OFF
GO
USE [Agil]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [Agil]
GO
/****** Object:  Table [dbo].[persona]    Script Date: 25/02/2022 11:17:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[persona](
	[ID] [int] NOT NULL,
	[usuario] [varchar](50) NOT NULL,
	[pass] [varchar](50) NOT NULL,
 CONSTRAINT [PK_tabla_persona] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Agil] SET  READ_WRITE 
GO
